# Generated by Django 5.0.6 on 2025-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('อื่นๆ', 'อื่นๆ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images/'),
        ),
    ]
