# Generated by Django 5.0.6 on 2025-03-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_admin_alter_user_user_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planplace',
            name='dt_visit',
        ),
    ]
